apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: ClusterIP   # Change this line from NodePort to ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080

  selector:
    io.kompose.service: api-gateway

