apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: ramazanakdag/discovery-server:latest
          name: discovery-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
