apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-tools
  name: kafka-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-tools
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-tools
    spec:
      containers:
        - command:
            - sleep
            - infinity
          image: wurstmeister/kafka:2.13-2.7.0
          name: kafka-tools
      restartPolicy: Always
