apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: leave-tracking-db-data
  name: leave-tracking-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
