apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: leave-tracking-service
  name: leave-tracking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leave-tracking-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: leave-tracking-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: ramazanakdag/leave-tracking-service:latest
          name: leave-tracking-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
