apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql-personnel-info
  name: mysql-personnel-info
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-personnel-info
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql-personnel-info
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: personnel_info_db
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: ramo
          image: mysql
          name: mysql-personnel-info
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: personnel-info-db-data
      restartPolicy: Always
      volumes:
        - name: personnel-info-db-data
          persistentVolumeClaim:
            claimName: personnel-info-db-data
