apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert -f d-c-new.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ui-service
  name: ui-service
spec:
  type: NodePort
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    io.kompose.service: ui-service
